/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistemafacturacionvisual.ConeccionBD;

/**
 *
 * @author jeniy
 */
public class GestorProductos extends javax.swing.JFrame {

    /**
     * Creates new form GestorProductos
     */
    String id_pro;
    public GestorProductos() {
        initComponents();
        bloquearbotonesInicio();
        bloqueartextosIniciar();
        
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    
    public void bloquearbotonesInicio(){
    jBntModificar.setEnabled(true);
    jBntEliminar.setEnabled(true);
    jBntGuardar.setEnabled(false);
    jBntActualizar.setEnabled(false);
 
    }
     
    
     public void desbloquearbotonesNuevo(){
    jBntNuevo.setEnabled(false);
    jBntModificar.setEnabled(false);
    jBntEliminar.setEnabled(false);
    jBntGuardar.setEnabled(true);
    jBntActualizar.setEnabled(false);
    
    }
    
    public void desbloquearbotonesGuardar(){
    jBntNuevo.setEnabled(true);
    jBntModificar.setEnabled(true);
    jBntEliminar.setEnabled(true);
    jBntGuardar.setEnabled(true);
    jBntActualizar.setEnabled(true);
    
    }
    
    public void bloqueartextosIniciar(){
    jTxtId.setEnabled(false);
    jTxtNombre.setEnabled(false);
    jTxtPrecio.setEnabled(false);
    jTxtStock.setEnabled(false);
    jTxtEstado.setEnabled(false);
    }
    
    public void desbloqueartextosIniciar(){
    jTxtId.setEnabled(true);
    jTxtNombre.setEnabled(true);
    jTxtPrecio.setEnabled(true);
    jTxtStock.setEnabled(true);
    jTxtEstado.setText("DISPONIBLE");
    jTxtEstado.setEnabled(false);
    }
        
    public void desbloquearTextoModificar() {
        if (!jTxtId.getText().isEmpty()) {
            jTxtId.setEnabled(false);
            jTxtNombre.setEnabled(true);
            jTxtPrecio.setEnabled(true);
            jTxtStock.setEnabled(true);
            jTxtEstado.setEnabled(true);
        }
    }
    
    public void limpiarTextos(){
    jTxtId.setText("");
    jTxtNombre.setText("");
    jTxtPrecio.setText("");
    jTxtStock.setText("");
    jTxtEstado.setText("");
    }
    
    public void controlarIngresoNumeros(KeyEvent e) {
    char caracter = e.getKeyChar();
        if(((caracter<'0' || caracter>'9'))){
         e.consume();
        }
    }
    
    public void controlarIngresoLetras(KeyEvent e){
    char caracter = e.getKeyChar();
        if((caracter < '0') || (caracter > '9')){
        }else{
        e.consume();
        }
    }
    
    public void controlarIngresoCostos(KeyEvent e){
          char c = e.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            e.consume();
        }
     }
     
    public void guardarNuevoProducto() {

        if (jTxtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el ID");
            jTxtId.requestFocus();
        } else if (jTxtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Nombre Producto");
            jTxtNombre.requestFocus();
        } else if (jTxtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Costo");
            jTxtPrecio.requestFocus();
        } else if (jTxtStock.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Stock");
            jTxtStock.requestFocus();
        } else {
            try {
                String id, nombre, disponibilidad;
                float costo;
                int stock;
                ConeccionBD cc = new ConeccionBD();
                Connection cn = cc.conectar();
                id = jTxtId.getText();
                nombre = jTxtNombre.getText();
                costo = Float.parseFloat(jTxtPrecio.getText());
                disponibilidad = jTxtEstado.getText();
                stock = Integer.parseInt(jTxtStock.getText());

                String sql = "";
                sql = "insert into productos(ID_PRO,NOM_PRO,PRE_PRO,EST_PRO,STOCK_PRO) values (?,?,?,?,?)";
                PreparedStatement psd = cn.prepareStatement(sql);

                psd.setString(1, id);
                psd.setString(2, nombre);
                psd.setFloat(3, costo);
                psd.setString(4, disponibilidad);
                psd.setInt(5, stock);

                int n = psd.executeUpdate();

                if (n > 0) {
                    JOptionPane.showMessageDialog(null, "SE GUARDAO CORRECTAMENTE");
                    limpiarTextos();
                    bloqueartextosIniciar();
                    desbloquearbotonesGuardar();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }

    public void modificarDatosProductoBD(String id_pro) {

        try {
            ConeccionBD cc = new ConeccionBD();
            Connection cn = cc.conectar();

            String sql = "";
            sql = "select * from productos";
            Statement psd = null;
            psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            
            while (rs.next()) {
             
                if (id_pro.equals(rs.getString("ID_PRO"))) {
                    jTxtId.setText(rs.getString("ID_PRO"));
                    jTxtNombre.setText(rs.getString("NOM_PRO"));
                    jTxtPrecio.setText(rs.getString("PRE_PRO"));
                    jTxtEstado.setText(rs.getString("EST_PRO"));
                    jTxtStock.setText(rs.getString("STOCK_PRO"));

                } else if (id_pro.equals(null)) {
                    JOptionPane.showMessageDialog(null, "No exite el producto");
                }
                desbloquearTextoModificar();
                jTxtId.setEnabled(false);
                desbloquearbotonesGuardar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void obtenerProductoModificar() {
        jLblEstado.setVisible(true);
        jTxtEstado.setVisible(true);
        Id_Producto_Modificar pm = new Id_Producto_Modificar();
        pm.setVisible(true);
        this.dispose();
    }
    
    public void actualizarBD() {
        if (jTxtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el ID");
            jTxtId.requestFocus();
        } else if (jTxtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Nombre Producto");
            jTxtNombre.requestFocus();
        } else if (jTxtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Costo");
            jTxtPrecio.requestFocus();
        } else if (jTxtStock.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el Stock");
            jTxtStock.requestFocus();
        } else {
            try {
                ConeccionBD cc = new ConeccionBD();
                Connection cn = cc.conectar();
                String sql = "";
                sql = "update productos set NOM_PRO='" + jTxtNombre.getText()
                        + "',PRE_PRO='" + jTxtPrecio.getText()
                        + "',EST_PRO='" + jTxtEstado.getText()
                        + "',STOCK_PRO='" + jTxtStock.getText()
                        + "' where ID_PRO='" + jTxtId.getText() + "'";
                PreparedStatement psd = cn.prepareStatement(sql);
                int n = psd.executeUpdate();
                if (n > 0) {
                    limpiarTextos();
                    bloqueartextosIniciar();
                }
            } catch (SQLException ex) {
                Logger.getLogger(GestorProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public void eliminarStockProducto(){
    EliminarStockProductos eli = new EliminarStockProductos();
    eli.setVisible(true);
    this.dispose();
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBntNuevo = new javax.swing.JButton();
        jBntModificar = new javax.swing.JButton();
        jBntEliminar = new javax.swing.JButton();
        jBntGuardar = new javax.swing.JButton();
        jBntActualizar = new javax.swing.JButton();
        jBntCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jTxtStock = new javax.swing.JTextField();
        jTxtPrecio = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLblEstado = new javax.swing.JLabel();
        jTxtEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBntNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jBntNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntNuevo.setText("NUEVO");
        jBntNuevo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntNuevoActionPerformed(evt);
            }
        });

        jBntModificar.setBackground(new java.awt.Color(204, 204, 204));
        jBntModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntModificar.setText("MODIFICAR");
        jBntModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntModificarActionPerformed(evt);
            }
        });

        jBntEliminar.setBackground(new java.awt.Color(204, 204, 204));
        jBntEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntEliminar.setText("ELIMINAR");
        jBntEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntEliminarActionPerformed(evt);
            }
        });

        jBntGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jBntGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntGuardar.setText("GUARDAR");
        jBntGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntGuardarActionPerformed(evt);
            }
        });

        jBntActualizar.setBackground(new java.awt.Color(204, 204, 204));
        jBntActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntActualizar.setText("ACTUALIZAR");
        jBntActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBntActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBntActualizarActionPerformed(evt);
            }
        });

        jBntCancelar.setBackground(new java.awt.Color(204, 204, 204));
        jBntCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBntCancelar.setText("CANCELAR");
        jBntCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBntModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBntNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBntActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBntNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBntModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBntEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBntGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBntActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jBntCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTxtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtStockKeyTyped(evt);
            }
        });

        jTxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtPrecioKeyTyped(evt);
            }
        });

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jTxtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIdKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("STOCK:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PRECIO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID PRODUCTO:");

        jLblEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLblEstado.setText("ESTADO:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtId)
                    .addComponent(jTxtNombre)
                    .addComponent(jTxtPrecio)
                    .addComponent(jTxtStock)
                    .addComponent(jTxtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblEstado)
                    .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntEliminarActionPerformed
        eliminarStockProducto();
    }//GEN-LAST:event_jBntEliminarActionPerformed

    private void jBntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntGuardarActionPerformed
       guardarNuevoProducto();
    }//GEN-LAST:event_jBntGuardarActionPerformed

    private void jBntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntNuevoActionPerformed
        desbloquearbotonesNuevo();
        desbloqueartextosIniciar();
    }//GEN-LAST:event_jBntNuevoActionPerformed

    private void jTxtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIdKeyTyped
        controlarIngresoNumeros(evt);
    }//GEN-LAST:event_jTxtIdKeyTyped

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        controlarIngresoLetras(evt);
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jTxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPrecioKeyTyped
        controlarIngresoCostos(evt);
    }//GEN-LAST:event_jTxtPrecioKeyTyped

    private void jTxtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtStockKeyTyped
         controlarIngresoNumeros(evt);
    }//GEN-LAST:event_jTxtStockKeyTyped

    private void jBntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntModificarActionPerformed
        obtenerProductoModificar();
    }//GEN-LAST:event_jBntModificarActionPerformed

    private void jBntActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBntActualizarActionPerformed
       actualizarBD();
    }//GEN-LAST:event_jBntActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBntActualizar;
    private javax.swing.JButton jBntCancelar;
    private javax.swing.JButton jBntEliminar;
    private javax.swing.JButton jBntGuardar;
    private javax.swing.JButton jBntModificar;
    private javax.swing.JButton jBntNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtEstado;
    private javax.swing.JTextField jTxtId;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtPrecio;
    private javax.swing.JTextField jTxtStock;
    // End of variables declaration//GEN-END:variables
}
